# Railway Configuration

[build]
buildCommand = "cd api && pip install -r requirements.txt"

[deploy]
startCommand = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
PYTHON_VERSION = "3.9"
NODE_VERSION = "18"