name: ✨ Feature Request
description: Suggest a new feature for AutoCrate
title: "[FEATURE]: "
labels: ["enhancement", "needs-review"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea clearly.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: This feature aligns with AutoCrate's educational use license
          required: true
        - label: I understand this is an AI development showcase project
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - New Material Support (Aluminum, Steel, Composite)
        - Calculation Enhancement (ASTM standards)
        - GUI/User Interface Improvement
        - CAD Integration (Siemens NX)
        - Optimization Algorithm
        - Testing/Quality Assurance
        - Documentation/Educational Content
        - Performance Improvement
        - API/Integration
      validations:
        required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the current limitation or challenge
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed feature in detail
      placeholder: How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. Engineer needs to design aluminum crates for aerospace shipping
        2. Cost optimization for high-volume production
        3. Integration with existing CAD workflows

  - type: checkboxes
    id: requirements
    attributes:
      label: Technical Requirements
      description: What technical aspects should be considered?
      options:
        - label: Must maintain ASTM compliance
        - label: Requires new ASTM standard implementation
        - label: Needs GUI changes
        - label: Affects NX expression generation
        - label: Requires new testing strategies
        - label: Impacts performance significantly
        - label: Needs new documentation

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - High - Critical for project success
        - Medium - Important improvement
        - Low - Nice to have enhancement
      validations:
        required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: |
        If you have ideas about how this could be implemented, share them here
        (Technical details, AI-assisted development approaches, etc.)

  - type: textarea
    id: educational-value
    attributes:
      label: Educational Value
      description: |
        How would this feature enhance AutoCrate's value as an AI development showcase?
        What learning opportunities would it create?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to help implement this feature
        - label: I can provide domain expertise/requirements
        - label: I can help with testing and validation
        - label: I can contribute to documentation